### ISSUE TITLE
Having trouble connecting

### ISSUE THREAD

**Issue by kodek** [etheralm/libpurecool#19]
I noticed that Home Assistant (0.109.4) stopped connecting to my fan:
```
Error during setup of component dyson
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/dyson/__init__.py", line 97, in setup
    connected = device.auto_connect(timeout, retry)
  File "/usr/local/lib/python3.7/site-packages/libpurecool/dyson_pure_cool_link.py", line 140, in auto_connect
    return self._mqtt_connect()
  File "/usr/local/lib/python3.7/site-packages/libpurecool/dyson_pure_cool_link.py", line 161, in _mqtt_connect
    self._network_device.port)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

I tried from a Python shell within the HA container:

```
>>> from libpurecool.dyson import DysonAccount
>> dyson_account = DysonAccount(“<SNIP>”, “<SNIP>”, “GB”)
>> dyson_account.login()
False
```

Any way I can easily get more logs? Thanks!

**Comment by kodek** [comment]
I just tried to log in again from the Python shell, and it succeeded. I’m going to investigate a bit more and reopen this if needed. Sorry about that!

**Comment by etheralm** [comment]
No worries, I was about to suggest to wait for some time and try again. The dyson servers can be a bit flaky at times. Let me know if you still have issues.
